---
- name: Check if NGINX is installed
  package_facts:
    manager: "auto"

- name: Start NGINX
  become: yes
  service:
    name: nginx
    state: started
  when: "'nginx' in ansible_facts.packages"
