---
- name: install and uninstall some of the common archive tools
  hosts:
    - ubuntu1
    - centos1
  become: yes
  tasks:
  
    - name: uninstall
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - unzip
        - nano
      tags:
        - uninstall
        
    - name: install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - zip
        - unzip
        - gzip
        - nano
      tags:
        - install

